<a href="https://colab.research.google.com/github/Mvrkery/Data-Science-Bootcamp-Projects/blob/main/Python_for_data_analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

****content****
- review claas OOP
- review loop + dictionary
- try except
- assert
- csv , json,context manager
- web scaping
- numpy pandas sqlite sklearn

In [ ]:
#super class
from typing_extensions import Self
class Person:
      pass
      def __init__(self,name): #self is the object we buildt
          self.name = name
      def hay(self):
            print("hello world")
      def sayhi(self):
            print(f"Hi my name is {self.name}")

class Employee(Person):
      def __init__(self,name,company):
            super().__init__(name)
            self.company = company
      def potato(self):
            print("patato is very good")
      def sayhi(self):
            print(f"hi my name is {self.name} and i work at{self.company}")

In [ ]:
toy = Person("toy")
john = Employee("john","google")
toy.sayhi()
john.sayhi()
john.hay()
toy.potato()

Hi my name is toy
hi my name is john and i work atgoogle
hello world


AttributeError: ignored

In [ ]:
# Superclass
class Person:
    def __init__(self, name):
        self.name = name

    def sayhi(self):
        print(f"Hi, my name is {self.name}")


# Subclass
class Employee(Person):
    def __init__(self, name, company):
        super().__init__(name)
        self.company = company

    def sayhi(self):
        print(f"Hi, my name is {self.name} and I work at {self.company}")


# Create instances
toy = Person("Toy")
john = Employee("John", "Google")

# Call sayhi() method
toy.sayhi()  # Output: Hi, my name is Toy
john.sayhi()  # Output: Hi, my name is John and I work at Google


Hi, my name is Toy
Hi, my name is John and I work at Google


In [ ]:
# try-except block
try:
    1/0
except:
  print("this is error")

this is error


In [ ]:
# try-except block
try:
   # x= "hello"
   # x= int(x)
   x=10
except ZeroDivisionError:
  print("this is error")
except NameError:
  print("variable is not found")
except ValueError:
  print("Please check your data type again")
else:
  print("Done!")
finally:
  print("this is the last line")

Done!
this is the last line


In [ ]:
assert 1+1 == 5, "1+1 must be qual 2"

AssertionError: ignored

In [ ]:
def check_this(a: int, b: int): # type hint
  assert a+b >10,"a+b must more than 10"
  return a+b

In [ ]:
# check_this(1,2)
check_this(10,0)

AssertionError: ignored

In [ ]:
# function
def greeting(name):
      print("hello " + name)

In [ ]:
greeting()

hello


In [ ]:
# lamda function for simple function
greeting = lambda name:print("hello  " + name)

In [ ]:
greeting("john")

hello  john


In [ ]:
def odd_or_even(num):
  if num % 2 == 0:
          print("even")
  else:
          print("odd")

In [ ]:
odd_or_even = lambda num: "even" if num % 2 ==0 else "odd"


In [ ]:
odd_or_even(8)

'even'

In [ ]:
hello = lambda : print("hello")

In [ ]:
hello()

hello


In [ ]:
# review class
# try except
# assert 1+1 == 2 "error message"
# lambda function

In [ ]:
# list of colored balls
balls = ["red","red","green","blue","blue"]

In [ ]:
def summary(list_items):

    result = {} #empty dict
    for ball in balls:
        if ball in result:
          result[ball] += 1
        else:
          result[ball] = 1
    print(result) # for กับ print ต้องตรงกัน

In [ ]:
def summary(list_items):
    result = {}
    for item in list_items:
          if ball in result:
              result[item] += 1
          else:
              result[item] = 1

    return(result)


In [ ]:
summary(balls)

{'red': 2, 'green': 1, 'blue': 2}


In [ ]:
# comma separated value (csv file*)

In [ ]:
!pwd

/content


In [ ]:
!ls

hotel.csv  sample_data


In [ ]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
!mkdir newfolder

In [ ]:
!rmdir newfolder

In [ ]:
!echo hello

hello


In [ ]:
!cat  hotel.csv

id,hotel,location ,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,35
4,Seoul,Korea,30
5,Le Concord,USA,25

In [ ]:
import csv #module

try:

    file = open("hotel.csv")

    data = csv.reader(file)

    for row in data:
        print(row)

    file.close() #ต้องcloseไม่งั้นอาจจะไฟล์เสีย

except FileNotFoundError: # r ทำไม่ได้เลย python เลยเหมาะกับซอฟแวร์มากกว่า
        print("File Not found")
else:
        print("load data succesfully")

['id', 'hotel', 'location ', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'Le Concord', 'USA', '25']
load data succesfully


In [ ]:
#context manager เปิด และปิด ไฟล์ ด้วย with
import csv
try:
    with open("hotel.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
except:
    print("Found some error")

['id', 'hotel', 'location ', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'Le Concord', 'USA', '25']


In [ ]:
csv_data = []
with open("hotel.csv", "r") as file: # with ปิดไฟล์อัติโนมัติ ไม่ต้อง file.close
        data = csv.reader(file)
        for row in data:
            csv_data.append(row)

print(csv_data)

[['id', 'hotel', 'location ', 'price'], ['1', 'Accor', 'Thailand', '50'], ['2', 'Ibis', 'Italy', '60'], ['3', 'London', 'UK', '35'], ['4', 'Seoul', 'Korea', '30'], ['5', 'Le Concord', 'USA', '25']]


In [ ]:
# modern python
import pandas as pd

df = pd.read_csv("hotel.csv")
df["price_double"] = df["price"]*2
df.to_csv("hotel_modified.csv")
df

id       hotel location   price  price_double
0   1       Accor  Thailand     50           100
1   2        Ibis     Italy     60           120
2   3      London        UK     35            70
3   4       Seoul     Korea     30            60
4   5  Le Concord       USA     25            50

In [ ]:
!cat hotel_modified.csv

,id,hotel,location ,price,price_double
0,1,Accor,Thailand,50,100
1,2,Ibis,Italy,60,120
2,3,London,UK,35,70
3,4,Seoul,Korea,30,60
4,5,Le Concord,USA,25,50


In [ ]:
# write csv file
# "W" write mode
import csv

headers = ["id","name","age"]
data = [
    [1 , "toy" , 25],
    [2 , "jisoo" , 26],
    [3 , "john" , 32]
]


with open("newfile.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [ ]:
!cat newfile.csv

id,name,age
1,toy,25
2,jisoo,26
3,john,32


In [ ]:
result = []
with open("newfile.csv","r") as file:
        data = csv.reader(file)
        for row in data:
            result.append(row)
print(result)

[['id', 'name', 'age'], ['1', 'toy', '25'], ['2', 'jisoo', '26'], ['3', 'john', '32']]


In [ ]:
# regular expression

import re
text = "a duck walks in to a bar"

result = re.search("duck",text)[0] # True ,False # เอาตัวที่ 0 จาก duck  ทั้งหมด

if result:
    print( "Duck found")
else:
    print( "Duck not found")

Duck found


In [ ]:
# regular expression

from re import search
text = "a duck walks in to a bar"

search("duck",text)[0] # เอาตัวที่ 0

'duck'

In [ ]:
from re import search
text = "a duck walks in to a bar"
search ("duck",text)[0]


'duck'

In [ ]:
# list comprehension
numbers =[1,2,3,4,5]

In [ ]:
result = [num*2 for num in numbers ]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
even_nums = []

for num in numbers :
    if num % 2 == 0:
        even_nums.append(num)
print(even_nums)

[2, 4]


In [ ]:
oddNums = [num for num in numbers if num%2 ==1]
evenNums = [num for num in numbers if num%2 ==0]
print(oddNums,evenNums)

[1, 3, 5] [2, 4]


In [ ]:
# json = java script object notation
!ls *.json # * match anything with

toy.json


In [ ]:
import json

with open("toy.json","r") as file:
    data = json.load(file)

In [ ]:
data
data["age"]

34

In [ ]:
# create new .jason file
school = {
    "name": "bootcamp",
    "batch":7,
    "duration":"4 months"
}
with open("newjsonfile.json","w") as file:
    json.dump(school,file)

In [ ]:
!cat newjsonfile.json

{"name": "bootcamp", "batch": 7, "duration": "4 months"}

In [ ]:
# API get request
import requests

url = "https://swapi.dev/api/people/1"

result = requests.get(url)
result.text
data_json = result.json()
data_json["name"]

'Luke Skywalker'

In [ ]:
from requests import get
from time import sleep

nums = list(range(1,6))
result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}"
    response = get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)
    print(result)
    sleep(1)

print(result)

[['Luke Skywalker', '172', '77', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]


In [ ]:
import pandas as pd

df = pd.DataFrame(result,columns=["name","height","mass","gender"])
df
df.to_csv("starwarapi.csv")

In [ ]:
# web scraping
# gazpacho

In [ ]:
!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7462 sha256=8afb6361a9e51315964667df54f50ad91f93a2b6c07d23ce58eea9cdccef10b8
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
!pip list | grep "^gaz"

gazpacho                         1.1


In [ ]:
!pip install requests

In [ ]:
from gazpacho import Soup
import requests
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

headers = {"Accept-Language": "en-US,en;q=0.5"} #เปลี่ยนภาษาเวลาได้output เป็นภาษจีน เพราะเซิฟมันอยู่จีน

response = requests.get(url, headers=headers)

imdb = Soup(response.text)

imdb.find("h3")[0].strip()

'1. The Shawshank Redemption (1994)'

In [ ]:
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc&language=en"

response = get(url)
imdb = Soup(response.text) #simplify for use imdb.find("title")

header = imdb.find("h3")[0].strip()
print(header)
print(response.status_code)


1. The Shawshank Redemption (1994)
200


In [ ]:
title_list =imdb.find("h3",{"class":"lister-item-header"})
for title in title_list:
    print(title.strip())

1. The Shawshank Redemption (1994)
2. The Godfather (1972)
3. The Dark Knight (2008)
4. Schindler's List (1993)
5. 12 Angry Men (1957)
6. The Lord of the Rings: The Return of the King (2003)
7. The Godfather Part II (1974)
8. Pulp Fiction (1994)
9. Spider-Man: Across the Spider-Verse (2023)
10. Inception (2010)
11. Fight Club (1999)
12. The Lord of the Rings: The Fellowship of the Ring (2001)
13. Forrest Gump (1994)
14. The Good, the Bad and the Ugly (1966)
15. The Lord of the Rings: The Two Towers (2002)
16. Interstellar (2014)
17. Goodfellas (1990)
18. One Flew Over the Cuckoo's Nest (1975)
19. The Matrix (1999)
20. Star Wars: Episode V - The Empire Strikes Back (1980)
21. Oppenheimer (2023)
22. Se7en (1995)
23. The Silence of the Lambs (1991)
24. Saving Private Ryan (1998)
25. Terminator 2: Judgment Day (1991)
26. Star Wars: Episode IV - A New Hope (1977)
27. The Green Mile (1999)
28. Spirited Away (2001)
29. City of God (2002)
30. Life Is Beautiful (1997)
31. It's a Wonderful Life 

In [ ]:
titles = [title.strip() for title in title_list]
print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. 12 Angry Men (1957)', '6. The Lord of the Rings: The Return of the King (2003)', '7. The Godfather Part II (1974)', '8. Pulp Fiction (1994)', '9. Spider-Man: Across the Spider-Verse (2023)', '10. Inception (2010)', '11. Fight Club (1999)', '12. The Lord of the Rings: The Fellowship of the Ring (2001)', '13. Forrest Gump (1994)', '14. The Good, the Bad and the Ugly (1966)', '15. The Lord of the Rings: The Two Towers (2002)', '16. Interstellar (2014)', '17. Goodfellas (1990)', "18. One Flew Over the Cuckoo's Nest (1975)", '19. The Matrix (1999)', '20. Star Wars: Episode V - The Empire Strikes Back (1980)', '21. Oppenheimer (2023)', '22. Se7en (1995)', '23. The Silence of the Lambs (1991)', '24. Saving Private Ryan (1998)', '25. Terminator 2: Judgment Day (1991)', '26. Star Wars: Episode IV - A New Hope (1977)', '27. The Green Mile (1999)', '28. Spirited Away (2

In [ ]:
runtimes = imdb.find("span",{"class":"runtime"})
runtimes = [runtime.strip() for runtime in runtimes]
print(runtimes)


['142 min', '175 min', '152 min', '195 min', '96 min', '201 min', '202 min', '154 min', '140 min', '148 min', '139 min', '178 min', '142 min', '178 min', '179 min', '169 min', '145 min', '133 min', '136 min', '124 min', '180 min', '127 min', '118 min', '169 min', '137 min', '121 min', '189 min', '125 min', '130 min', '116 min', '130 min', '207 min', '133 min', '130 min', '151 min', '132 min', '117 min', '155 min', '116 min', '106 min', '110 min', '150 min', '109 min', '106 min', '88 min', '119 min', '89 min', '112 min', '102 min', '165 min']


In [ ]:
import pandas as pd
# ถ้า pd.DataFrame ใช้ไม่ได้ให้ import request ใหม่
df=pd.DataFrame({
    "title" : titles,
    "runtime":runtimes
})

df.head()
df.to_csv("imdb_data.csv")
df.head()

title  runtime
0  1. The Shawshank Redemption (1994)  142 min
1             2. The Godfather (1972)  175 min
2           3. The Dark Knight (2008)  152 min
3          4. Schindler's List (1993)  195 min
4              5. 12 Angry Men (1957)   96 min

In [ ]:
#flash fill in excel -> CTRL + E

Basic Data Tools
- numpy
- pandas
- sklearn

In [ ]:
# numpy = numerical python
import numpy as np
num = [1,2,3,4,5]
print(num)
print(num * 2)
print([x*2 for x in num])
num_arr = np.array(num)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]


In [ ]:
print(num_arr * 2 ,num_arr + 2, num_arr / 5)

[ 2  4  6  8 10] [3 4 5 6 7] [0.2 0.4 0.6 0.8 1. ]


In [ ]:
# statistical basic calculation
np.sum(num_arr)
np.mean(num_arr)
np.std(num_arr)
np.min(num_arr)
np.max(num_arr)
len(num_arr)
num_arr.std()


1.4142135623730951

In [ ]:
# matrix 2D-array
m1 = np.array([
               [1,2],
               [3,4]
               ])
m1
m1 * 5

array([[ 5, 10],
       [15, 20]])

In [ ]:
m2 = np.array([
    [5,5],
    [4,2]
])

In [ ]:
print(m1,"\n"*2,m2)

[[1 2]
 [3 4]] 

 [[5 5]
 [4 2]]


In [ ]:
m1 * m2 #metix ไม่ได้คูณกันอย่างนี้

array([[ 5, 10],
       [12,  8]])

In [ ]:
m1.dot(m2) #คูณแบบนี้
np.dot(m1,m2)

array([[13,  9],
       [31, 23]])

In [ ]:
# intro to pandas
!cat hotel.csv

id,hotel,location ,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,35
4,Seoul,Korea,30
5,Le Concord,USA,25

In [ ]:
import pandas as pd
import numpy as np

hotel = pd.read_csv("hotel.csv")
hotel

id       hotel location   price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  Le Concord       USA     25

In [ ]:
hotel.shape #(row,col)

(5, 4)

In [ ]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         5 non-null      int64 
 1   hotel      5 non-null      object
 2   location   5 non-null      object
 3   price      5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [ ]:
hotel.describe()

id     price
count  5.000000   5.00000
mean   3.000000  40.00000
std    1.581139  14.57738
min    1.000000  25.00000
25%    2.000000  30.00000
50%    3.000000  35.00000
75%    4.000000  50.00000
max    5.000000  60.00000

In [ ]:
hotel.describe(include="all")

id  hotel location      price
count   5.000000      5         5   5.00000
unique       NaN      5         5       NaN
top          NaN  Accor  Thailand       NaN
freq         NaN      1         1       NaN
mean    3.000000    NaN       NaN  40.00000
std     1.581139    NaN       NaN  14.57738
min     1.000000    NaN       NaN  25.00000
25%     2.000000    NaN       NaN  30.00000
50%     3.000000    NaN       NaN  35.00000
75%     4.000000    NaN       NaN  50.00000
max     5.000000    NaN       NaN  60.00000

In [ ]:
hotel["hotel"]
hotel["price"]
hotel.price

0    50
1    60
2    35
3    30
4    25
Name: price, dtype: int64

In [ ]:
hotel["vat"] = hotel['price'] * 0.07
hotel

# r version
# hotel$vat <- hotel$price * 0.07

id      hotel location   price   vat
0   1      Accor  Thailand     50  3.50
1   2       Ibis     Italy     60  4.20
2   3     London        UK     35  2.45
3   4      Seoul     Korea     30  2.10
4   5  Le cocord       USA     25  1.75

In [ ]:
# query (filter rows)
hotel.query("price > 40")

# r version
# filter(hotel, price > 40)
# hotel %>% filter(price >40)

id  hotel location   price
0   1  Accor  Thailand     50
1   2   Ibis     Italy     60

In [ ]:
# query (filter rows)
value_hotel = hotel.query("price <= 40")
value_hotel.to_csv("value_hotel.csv")
hotel

id       hotel location   price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  Le Concord       USA     25

In [ ]:

# drop column
hotel.drop("vat",axis = 1,inplace = True) #drop เหมือน filter แต่ ทั้งหมดยังอยู่เหมือนเดิม ไม่ต้อง reassign
hotel.drop("vat",axis = 1) # อันนี้ลบจริง

In [ ]:
hotel

id       hotel location   price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  Le Concord       USA     25

In [ ]:
import pandas
hotel.query("price > 30 | id == 5 ")

id       hotel location   price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
4   5  Le Concord       USA     25

In [ ]:
# sklearn => machine learning most poopular python
# template in sklearn to train_test_split

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [ ]:
mtcars = pd.read_csv("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")

In [ ]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
# prepare 50-80% time
# mpg = f(hp,wt,am)
X = mtcars[ ["hp","wt","am"] ]
y = mtcars["mpg"]

In [ ]:
# split data 80% train ,20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
# train model
# model = LinearRegression()
#model = DecisionTreeRegressor()

model = RandomForestRegressor()
model.fit(X_train, y_train)
# model = RandomForestRegressor().fit(X_train, y_train)


# test model/ scoring
pred = model.predict(X_test)
pred

# MAE mean absolute error
mae = np.mean(np.absolute((y_test - pred)))

# MSE
mse = np.mean((y_test - pred)**2)

#--------------------------
mse2 = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)
mae = mean_absolute_error(y_test, pred)

# Print the evaluation results
print("Mean Squared Error:", mse)
print("R-squared:", r2)
print("Mean Absolute Error:", mae)
print(mae,mse)

Mean Squared Error: 9.554231857142812
R-squared: 0.7610491108706536
Mean Absolute Error: 2.22785714285714
2.22785714285714 9.554231857142812
